### ISSUE TITLE
Decide on markup for images

### ISSUE THREAD

**Issue by rexxars** [aptoma/drpublish-imbo-app#4]
We have to decide on a standard markup for the images inserted.

Here's what the app currently inserts:
```html
<div id="dp-plugin-element-imbo-25571415187374168" class="dp-plugin-element dp-plugin-imbo">
    <div class="dp-article-image-container">
        <img
            src="https://imbo-drp.vgnett.no/users/drp/images/a60fccd8ce0e3b39e94863a084ab3473.jpg?t%5B%5D=modulate%3As%3D125&amp;t%5B%5D=crop%3Awidth%3D2214%2Cheight%3D1875%2Cx%3D476%2Cy%3D572&amp;t%5B%5D=maxSize%3Awidth%3D552&amp;accessToken=4aacfedcb74757db9b780ad66970fd6f86be852e9734dcb66703f33f4b194b0a"
            alt=""
            data-transformations="[&quot;modulate:s=125&quot;,&quot;crop:width=2214,height=1875,x=476,y=572&quot;,&quot;maxSize:width=552&quot;]"
            data-image-identifier="a60fccd8ce0e3b39e94863a084ab3473"
            data-crop-parameters="{&quot;x&quot;:476,&quot;y&quot;:572,&quot;x2&quot;:2691,&quot;y2&quot;:2448,&quot;w&quot;:2214,&quot;h&quot;:1875}"
            data-crop-aspect-ratio="null"
        >

        <div class="dp-article-image-title">Terrible lighting</div>
        <div class="dp-article-image-description">
            André and Espen implementing creative solutions to a difficult working environment
        </div>

        <div class="dp-article-image-byline">
            <span class="dp-article-image-author">Espen Hovlandsdal</span>
            <span class="dp-article-image-source">Verdens Gang AS</span>
        </div>
    </div>
</div>
```

The URL will have transformations added to it, but each platform can regenerate a URL with a more fitting size should they need to, using a correctly configured Imbo client.

Does this look OK? Since the markup has to be parsed by DrPublish and a NewsML-representation should be able to present all this, I mean.

**Comment by androa** [comment]
Could a solution here be a Point of Interest based crop? The journalist chooses the most important POI (or several) within an image, and the view layer says how big the resulting picture should be. Then Imbo decides how to best fit the POI(s) within the specified size?

**Comment by mipli** [comment]
Not sure if that would work. What if it is an image of one person, than the POI would be face of that person. How would Imbo decide how to crop the image to only show a suitable amount of that person?

**Comment by Jocumsen** [comment]
@mipli, that should not be a problem - in fact, that is the exact scenario where the POI delivers on the promised idea.

Let's say we have a typical profile image of a standing person, sized 200px in width and 800px in height. If the Front End only wants square representations for images, then the 200x800 needs to be cropped to e.g. 200x200.

Historically, a simple crop mechanism would include the whole width, but cut out the top 300px and top bottom 300px. In some cases that might work fine, but for a standing person it would not.

However, with a set POI (e.g. the face of a person, let's say at location x=80 and y=110) stored in Imbo, the Front End wouldn't even need to know about the POI, but just say "give me a 200x200 version". Imbo would then use the POI to return the same width (all 200, even though the POI was slightly off center), but the POI-Y would result in the top 10px and the bottom 590px being cropped instead of the top/bottom 300px. The result would be a much better cropping, without Front End caring how.

So, the Front End does not care what is cropped, but it can rest assured that if Imbo has been told of a POI, that will be included in the crop. I believe that solves the use cases.

There *might* be some extremely rare cases where even such a magical crop might produce a weirdly cropped image, but I think those cases are negligible.

Note: I also believe a single POI would be sufficient. The added complexity needed to support multiple POIs, both technical and UX wise, can't be justified by such edge cases(e.g. a landscape mode picture of a group of people could be such a case. But, that is more acceptable than only showing the crotch of a person.)

I say we go for this solution!

**Comment by mipli** [comment]
Do you have a place where we can test the algorithm you're going to use for this?

As you say it should work for most cases and if the edge cases end up looking good enough I think this would be a nice solution. 

Even if it turns out that it isn't enough in the long run it'll be a lot better than any other default cropping, so having this feature is a good thing.

Are you thinking of adding this as a new crop type in Imbo?

**Comment by Jocumsen** [comment]
Hmm, I don't think we have a place where you could test - unless you are thinking of an imbo-stage?

I also believe this will be much better than default cropping, and thus good enough as an overall solution.

I wasn't thinking of adding this as a new crop *type*, but rather as a generic mechanism that kicks in when any crop is wanted. I guess we would need to solve this by offering two different functions for cropping: 
A) One function with only two parameters (the new size: width, height). Using this would automatically use the Point Of Interest to know what to crop away.
B)  Another function with more parameters (the new size, but also the specific coordinates for the area that should be used for the cropping). This would be equivalent to the current/old way of cropping.
